project:
  type: website
  output-dir: .

website:
  title: "Template"
  navbar:
    left:
      - href: index.qmd

format:
  revealjs:
    theme: css/custom.scss
    incremental: false   
    transition: slide
    background-transition: slide



